"use client";
import { LegalPage } from "@/components/sections/LegalPage";
import { useLang } from "@/lib/i18n";
const COPY = {
  en: { title: "Privacy Policy", lastUpdated: "June 1, 2025", sections: [{ heading: "1. Who we are", content: "Collective Audience SAS (France) and Collective Audience Inc. (USA) operate the platform at collectiveaudience.co." }, { heading: "2. Data we collect", content: "We collect data you provide directly (name, email, company when contacting us or subscribing to the newsletter), data collected automatically (log data, IP address, browser type), and audience data collected on publisher sites with your consent." }, { heading: "3. How we use your data", content: "To provide and improve our services, send newsletters you subscribed to, respond to inquiries, analyze platform usage, and serve relevant advertising. We do not sell personal data to third parties." }, { heading: "4. Cookies", content: "We use strictly necessary cookies for platform functionality and, with your consent, analytics cookies (Google Analytics, Matomo) and advertising cookies (TCF 2.x). See our Cookie Policy for details." }, { heading: "5. Data retention", content: "Contact form data: 3 years. Newsletter: until unsubscribe. Platform logs: 13 months. Audience data: per publisher agreement, maximum 13 months." }, { heading: "6. Your rights", content: "Under GDPR, you have the right to access, rectify, erase, restrict, and port your data, as well as to object to processing. Submit requests to privacy@collectiveaudience.co." }, { heading: "7. International transfers", content: "Data may be transferred to the US under Standard Contractual Clauses (SCCs). We maintain a data processing agreement with all sub-processors." }, { heading: "8. Contact & DPO", content: "Our DPO can be reached at dpo@collectiveaudience.co. EU inquiries: 33 rue La Fayette, 75009 Paris, France." }] },
  fr: { title: "Politique de confidentialité", lastUpdated: "1er juin 2025", sections: [{ heading: "1. Qui sommes-nous", content: "Collective Audience SAS (France) et Collective Audience Inc. (USA) exploitent la plateforme collectiveaudience.co." }, { heading: "2. Données collectées", content: "Nous collectons les données que vous nous fournissez directement (nom, email, entreprise lors d'un contact ou d'une inscription à la newsletter), les données collectées automatiquement (logs, adresse IP, type de navigateur), et les données d'audience collectées sur les sites éditeurs avec votre consentement." }, { heading: "3. Utilisation de vos données", content: "Pour fournir et améliorer nos services, envoyer les newsletters auxquelles vous êtes abonné, répondre aux demandes, analyser l'utilisation de la plateforme et diffuser de la publicité pertinente. Nous ne vendons pas vos données à des tiers." }, { heading: "4. Cookies", content: "Nous utilisons des cookies strictement nécessaires au fonctionnement de la plateforme et, avec votre consentement, des cookies analytiques (Google Analytics, Matomo) et publicitaires (TCF 2.x). Consultez notre Politique de cookies pour plus de détails." }, { heading: "5. Conservation des données", content: "Formulaire de contact : 3 ans. Newsletter : jusqu'à désinscription. Logs plateforme : 13 mois. Données d'audience : selon accord éditeur, maximum 13 mois." }, { heading: "6. Vos droits", content: "En vertu du RGPD, vous disposez du droit d'accès, de rectification, d'effacement, de limitation, de portabilité et d'opposition. Soumettez vos demandes à privacy@collectiveaudience.co." }, { heading: "7. Transferts internationaux", content: "Les données peuvent être transférées vers les États-Unis en vertu des Clauses Contractuelles Types (CCT). Nous maintenons un accord de traitement de données avec tous les sous-traitants." }, { heading: "8. Contact & DPO", content: "Notre DPO est joignable à dpo@collectiveaudience.co. Demandes UE : 33 rue La Fayette, 75009 Paris, France." }] },
};
export default function Page() {
  const { lang } = useLang();
  const c = COPY[lang];
  return <LegalPage title={c.title} lastUpdated={c.lastUpdated} sections={c.sections} />;
}
