"use client";
import { LegalPage } from "@/components/sections/LegalPage";
import { useLang } from "@/lib/i18n";
const COPY = {
  en: { title: "Cookie Policy", lastUpdated: "June 1, 2025", sections: [{ heading: "1. What are cookies?", content: "Cookies are small text files placed on your device when you visit a website. They help websites remember your preferences and improve your experience." }, { heading: "2. Cookies we use", content: "Strictly necessary: session management and security (cannot be opted out). Analytics: Google Analytics and Matomo to measure audience and improve the platform (opt-in). Advertising: IAB TCF 2.x-compliant signals for targeted advertising on publisher sites (opt-in per publisher CMP)." }, { heading: "3. How to manage cookies", content: "You can manage cookie preferences at any time via the consent banner on this site, your browser settings, or opt-out tools: Google Analytics Opt-out, Matomo Opt-out." }, { heading: "4. Third-party cookies", content: "Publisher sites in our network use their own CMPs compliant with IAB TCF 2.x. Collective Audience only processes audience data where users have granted consent." }, { heading: "5. Retention", content: "Session cookies expire when you close your browser. Persistent analytics cookies expire after 13 months. Advertising signal data is retained per publisher agreement, maximum 13 months." }] },
  fr: { title: "Politique de cookies", lastUpdated: "1er juin 2025", sections: [{ heading: "1. Que sont les cookies ?", content: "Les cookies sont de petits fichiers texte placés sur votre appareil lorsque vous visitez un site web. Ils aident les sites à mémoriser vos préférences et à améliorer votre expérience." }, { heading: "2. Cookies utilisés", content: "Strictement nécessaires : gestion de session et sécurité (non optionnels). Analytique : Google Analytics et Matomo pour mesurer l'audience et améliorer la plateforme (opt-in). Publicitaires : signaux conformes IAB TCF 2.x pour la publicité ciblée sur les sites éditeurs (opt-in par CMP éditeur)." }, { heading: "3. Gestion des cookies", content: "Vous pouvez gérer vos préférences de cookies à tout moment via la bannière de consentement, les paramètres de votre navigateur, ou les outils d'opt-out : Google Analytics Opt-out, Matomo Opt-out." }, { heading: "4. Cookies tiers", content: "Les sites éditeurs de notre réseau utilisent leurs propres CMP conformes IAB TCF 2.x. Collective Audience ne traite les données d'audience que là où les utilisateurs ont accordé leur consentement." }, { heading: "5. Conservation", content: "Les cookies de session expirent à la fermeture du navigateur. Les cookies analytiques persistants expirent après 13 mois. Les données de signaux publicitaires sont conservées selon l'accord éditeur, maximum 13 mois." }] },
};
export default function Page() {
  const { lang } = useLang();
  const c = COPY[lang];
  return <LegalPage title={c.title} lastUpdated={c.lastUpdated} sections={c.sections} />;
}
