"use client";
import { LegalPage } from "@/components/sections/LegalPage";
import { useLang } from "@/lib/i18n";
const COPY = {
  en: { title: "Terms of Use", lastUpdated: "June 1, 2025", sections: [{ heading: "1. Acceptance of Terms", content: "By accessing or using the Collective Audience platform and website, you agree to be bound by these Terms of Use." }, { heading: "2. Platform Access", content: "Collective Audience grants you a limited, non-exclusive, non-transferable license to access and use the platform for your internal business purposes, subject to these terms and your subscription agreement." }, { heading: "3. Acceptable Use", content: "You may not use the platform to violate any applicable laws, infringe intellectual property rights, distribute malware, conduct fraudulent activity, or circumvent any technical restrictions." }, { heading: "4. Intellectual Property", content: "All content, trademarks, and technology on the platform are owned by Collective Audience or its licensors. You may not reproduce, modify, or distribute them without prior written consent." }, { heading: "5. Data & Privacy", content: "Use of the platform is also governed by our Privacy Policy. By using the platform, you consent to our data practices as described therein." }, { heading: "6. Limitation of Liability", content: "To the maximum extent permitted by law, Collective Audience shall not be liable for indirect, incidental, special, consequential, or punitive damages arising from your use of the platform." }, { heading: "7. Governing Law", content: "These terms are governed by French law (for EU users) or New York law (for US users). Disputes shall be submitted to the courts of Paris or New York respectively." }] },
  fr: { title: "Conditions d'utilisation", lastUpdated: "1er juin 2025", sections: [{ heading: "1. Acceptation des conditions", content: "En accédant ou en utilisant la plateforme et le site web de Collective Audience, vous acceptez d'être lié par ces Conditions d'utilisation." }, { heading: "2. Accès à la plateforme", content: "Collective Audience vous accorde une licence limitée, non exclusive et non transférable pour accéder à la plateforme à des fins professionnelles internes, sous réserve de ces conditions et de votre accord d'abonnement." }, { heading: "3. Utilisation acceptable", content: "Vous ne pouvez pas utiliser la plateforme pour violer des lois applicables, porter atteinte aux droits de propriété intellectuelle, distribuer des malwares, mener des activités frauduleuses ou contourner des restrictions techniques." }, { heading: "4. Propriété intellectuelle", content: "Tout le contenu, les marques et la technologie de la plateforme appartiennent à Collective Audience ou à ses concédants. Vous ne pouvez pas les reproduire, modifier ou distribuer sans consentement écrit préalable." }, { heading: "5. Données & Confidentialité", content: "L'utilisation de la plateforme est également régie par notre Politique de confidentialité. En utilisant la plateforme, vous consentez à nos pratiques de données telles que décrites." }, { heading: "6. Limitation de responsabilité", content: "Dans la mesure maximale permise par la loi, Collective Audience ne sera pas responsable des dommages indirects, accessoires, spéciaux, consécutifs ou punitifs découlant de votre utilisation de la plateforme." }, { heading: "7. Droit applicable", content: "Ces conditions sont régies par le droit français (pour les utilisateurs de l'UE) ou le droit de New York (pour les utilisateurs américains). Les litiges seront soumis aux tribunaux de Paris ou de New York respectivement." }] },
};
export default function Page() {
  const { lang } = useLang();
  const c = COPY[lang];
  return <LegalPage title={c.title} lastUpdated={c.lastUpdated} sections={c.sections} />;
}
