"use client";
import { LegalPage } from "@/components/sections/LegalPage";
import { useLang } from "@/lib/i18n";
const COPY = {
  en: { title: "Accessibility Statement", lastUpdated: "June 1, 2025", sections: [{ heading: "Our commitment", content: "Collective Audience is committed to making our website and platform accessible to all users, including people with disabilities. We aim to conform to WCAG 2.1 Level AA guidelines." }, { heading: "Current status", content: "Key measures include: sufficient color contrast ratios (4.5:1 minimum), keyboard navigation support for all interactive elements, ARIA labels on all icon-only buttons, skip-to-content link, and alt text on all meaningful images." }, { heading: "Known issues", content: "We are aware of some areas that still need improvement, particularly in our ad format gallery and interactive demos. We are working to resolve these in upcoming releases." }, { heading: "Feedback & contact", content: "If you experience accessibility barriers, please contact us at accessibility@collectiveaudience.co. We aim to respond within 5 business days." }, { heading: "Formal complaints", content: "If you are not satisfied with our response, you may escalate to the relevant national accessibility authority (DINUM in France, AbilityNet in the UK)." }] },
  fr: { title: "Déclaration d'accessibilité", lastUpdated: "1er juin 2025", sections: [{ heading: "Notre engagement", content: "Collective Audience s'engage à rendre notre site web et notre plateforme accessibles à tous les utilisateurs, y compris les personnes en situation de handicap. Nous visons la conformité aux WCAG 2.1 Niveau AA." }, { heading: "État actuel", content: "Mesures clés : ratios de contraste des couleurs suffisants (minimum 4,5:1), navigation au clavier pour tous les éléments interactifs, labels ARIA sur tous les boutons icône, lien d'évitement et texte alternatif sur toutes les images significatives." }, { heading: "Problèmes connus", content: "Nous avons connaissance de certaines zones qui nécessitent encore des améliorations, notamment dans notre galerie de formats publicitaires et les démos interactives. Nous travaillons à les résoudre dans les prochaines versions." }, { heading: "Retours & contact", content: "Si vous rencontrez des obstacles d'accessibilité, contactez-nous à accessibility@collectiveaudience.co. Nous visons à répondre dans les 5 jours ouvrables." }, { heading: "Réclamations formelles", content: "Si vous n'êtes pas satisfait de notre réponse, vous pouvez escalader auprès de l'autorité nationale compétente (DINUM en France, AbilityNet au Royaume-Uni)." }] },
};
export default function Page() {
  const { lang } = useLang();
  const c = COPY[lang];
  return <LegalPage title={c.title} lastUpdated={c.lastUpdated} sections={c.sections} />;
}
